@host=http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQHRlc3QuY29tIiwicm9sZXMiOlsiYmFzaWMiXSwiaWF0IjoxNjE2MTkwNTYyLCJleHAiOjE2MTYxOTA2MjJ9.FofSc8L-BekGTNX463R4kcyMvWmDxs-PFZFw0t021-k

GET {{host}}

### GET DASHBOARD

GET {{host}}/dashboard
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### GET ADMIN

GET {{host}}/admin
Authorization: Bearer {{accessToken}}


### GET PROJECTS

GET {{host}}/projects
Authorization: Bearer {{accessToken}}


### GET PROJECT

GET {{host}}/projects/3
Authorization: Bearer {{accessToken}}


### DELETE PROJECT

DELETE {{host}}/projects/2
Authorization: Bearer {{accessToken}}
